[theme]
base="light"
primaryColor="#0F172A"              # azul muy oscuro elegante
backgroundColor="#F9FAFB"           # gris muy suave
secondaryBackgroundColor="#FFFFFF"  # cards blancas
textColor="#0F172A"
font="sans serif"
